#!/usr/bin/env python

import ast
import json
import sys

def json_to_ast(node):
    if isinstance(node, dict):
        node_type = getattr(ast, node["type"])
        kwargs = {k: json_to_ast(v) for k, v in node.items() if k != "type"}
        kwargs = {'type_ignores': [], 'decorator_list': [], 'lineno': 0, **kwargs}
        return node_type(**kwargs)
    elif isinstance(node, list):
        return [json_to_ast(subnode) for subnode in node]
    else:
        return node

if __name__ == "__main__":
    print(ast.unparse(json_to_ast(json.load(sys.stdin))))
