#!/bin/bash

cmd=$(printf ' %q' "$@" | sed 's/^[[:space:]]*//')

dir=$(basename "$(pwd)")

bash -c "$cmd"
code=$?
if [ $code -eq 0 ]; then
  notify-success "\`$cmd\` succeeded in $dir"
else
  notify-fail "\`$cmd\` failed in $dir"
  exit $code
fi
