#!/bin/bash

# https://jvns.ca/til/fzf-preview-git-commits/
commit=${1:-HEAD}
git show --stat=120 --format="" "$commit" | \
  grep -E '^\s*\S+.*\|' | \
  fzf --ansi \
      --disabled \
      --bind 'j:down,k:up,q:abort' \
      --preview="echo {} | sed 's/|.*//' | xargs -I% git show --color=always $commit -- %" \
      --preview-window=right:60%
