#!/bin/bash

set -e

mainBranch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
toRevert=$(git diff $mainBranch... --name-only | directories-and-files | sort -u | fzf --ansi \
  --disabled \
  --bind 'j:down,k:up,q:abort' \
  --preview="git diff $mainBranch... -- {}" \
  --preview-window=right:60%)

if [ -z "$toRevert" ]; then
  echo "No directories or files selected."
  exit 1
fi

git diff $mainBranch... -R -- $toRevert | patch -p1
