#!/bin/bash

source=$1
dest=$2
cmd=$3

case $cmd in
  pad)
    size=$4
    magick convert \
      -background white \
      -flatten "$source" \
      -define icon:auto-resize=64,48,32,16 \
      "$dest"
    ;;
  round)
    radius=$4
    magick convert \
      -background white \
      -flatten "$source" \
      \( +clone -alpha extract \
        -draw "fill black polygon 0,0 0,$radius $radius,0 fill white circle $radius,$radius $radius,0" \
        \( +clone -flip \) -compose Multiply -composite \
        \( +clone -flop \) -compose Multiply -composite \
      \) \
      -alpha off \
      -compose CopyOpacity \
      -composite \
      -define icon:auto-resize=64,48,32,16 \
      "$dest"
    ;;
  *)
    magick convert \
      "$source" \
      -define icon:auto-resize=64,48,32,16 \
      "$dest"
    ;;
esac
