#!/bin/bash

set -e

cmd=$*

# Find the non-active pane
target=.$(tmux list-panes -F '#{pane_active} #{pane_index}' | grep -v '^1 ' | cut -d' ' -f2 | head -n 1)

# Ensure pane is not zoomed
if tmux list-panes -t "$target" -F '#F' | grep -q "Z"; then
  tmux resize-pane -t "$target" -Z
fi

# Ensure pane is not in copy mode
tmux send -t "$target" -X cancel 2>/dev/null || true

tmux send -t "$target" "$*" C-m
