#!/bin/bash

if [ -n "$1" ] && [ -n "$(tmux list-sessions -F '#S' | grep "^$1\$")" ]; then
  tmux -2 attach -t $1
elif cd $1; then
  if [ -e ".tmuxrc" ]; then
    tmux -2 new \; source-file .tmuxrc \; attach
  else
    tmux -2 new \; attach
  fi
else
  echo "'$1' directory or session does not exist"
  exit 1
fi
